alias c='clear'

alias gs='git status'
alias ga='git add --all'
alias gc='git commit'
alias gds='git diff --staged'
alias gm='git merge'
alias gb='git branch'
alias gba='git branch -a'
alias gf='git fetch'
alias gp='git push'
alias gr='git reset'
alias go='git checkout'
alias gl='git log --oneline'
alias gpu='git pull'
